network_statistic_home:
    path:     /admin/parse
    defaults: { _controller: NetworkStatisticBundle:Parse:home }

network_statistic_parse:
    path:     /admin/parse/{startYear}/{endYear}
    defaults: { _controller: NetworkStatisticBundle:Parse:parse }
    requirements:
        _method: GET
        startYear: \d+
        endYear: \d+

network_statistic_calc_achievements:
    path:     /admin/parse/calc
    defaults: { _controller: NetworkStatisticBundle:Parse:calc }

network_statistic_find_student:
    path:     /api/find_student/{name}
    defaults: { _controller: NetworkUserBundle:Achievement:findStudent }

network_statistic_set_student:
    path:     /api/set_student/{id}
    defaults: { _controller: NetworkUserBundle:Achievement:setStudentForUser }
